name="LangChain example code."
author="SquirrelYe"
time="2023-05-22"

run-model:
	@echo "Run model..."
	@python3 ./01.model.py

run-prompt:
	@echo "Run prompt..."
	@python3 ./02.prompt.py

run-chain:
	@echo "Run chain..."
	@python3 ./03.chain.py