name="LangChain example code."
author="SquirrelYe"
time="2023-05-22"

run_001_getting_started:
	@echo "Run model..."
	@python3 ./001_getting_started/getting_started.py

run_002_custom_agents:
	@echo "Run model..."
	@python3 ./002_custom_agents/custom_agents.py

run_003_custom_agent_with_tool_retrieval:
	@echo "Run model..."
# @python3 ./003_custom_agent_with_tool_retrieval/tool_retriever.py
	@python3 ./003_custom_agent_with_tool_retrieval/index.py
